server:
  port: 2223


eureka:
  instance:
    hostname: localhost
  client:
    service-url.defaultZone: http://localhost:7000/eureka/

spring:
    application:
      name: spring-user
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: test
        auto-offset-reset: earliest




